# https://docs.codecov.io/docs/commit-status#branches
ignore:
  - "tests/"
  - "tests"
  - "tests/cases"
  - "test/cases/"

coverage:
  status:
    project:
      default:
        branches:
          - main
        paths:
          - "src"
        target: 80%
        threshold: 5%
        if_ci_failed: error
        flags:
          - unit
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        # advanced
          - main
        if_ci_failed: error
        only_pulls: true
        paths:
          - "src"
