on: ["push", "pull_request"]

name: build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: npm install
              run: npm install

            - name: Add prettier
              run: npm install -g prettier --dev

            - name: Check code style
              run: npm run prettier --config ./.prettierrc.yaml --check  ./src/*

            - name: Build project
              run: npm run build

            - name: Test and generate coverage report
              run: npm run test --coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
              name: codecov-umbrella
              fail_ci_if_error: false
